### ISSUE TITLE
changes to animations lesson:

### ISSUE THREAD

**Issue by CaitlinBate** [ocean-tracking-network/2023-canssi-ecr-workshop#15]
basic animations
- line 17 --- specify `dplyr::filter(passed_filter != FALSE) %>% `
- line 39 -- name plot `labs(title = "NSBS animation",`

pathroutr
- line 16 --- specify `dplyr::filter(passed_filter != FALSE) %>% `
- line 50 took 3 mins!
- line 55 took 2 mins
- need to add `install.packages('geodata')` to the setup eventually, just as a note :P 
- I'm confused because pathroutr plot goes -around- land which is perfect but the animation crosses land??i thought the entire point of pathroutr vs basic is because it DOESNT cross land?

are we using "intro gis spdplyr" lesson or can this be deleted from master?

changes will need to be done in both master and gh-pages

**Comment by jackVanish** [comment]
Changes to code here; if they pass muster I will edit gh-pages also https://github.com/ocean-tracking-network/2023-canssi-ecr-workshop/pull/17

**Comment by CaitlinBate** [comment]
gh-pages changes can go into #14 i think

added my review on #17

**Comment by jackVanish** [comment]
Just pushed up the remaining changes to GH-pages, so this should be clear.
