### ISSUE TITLE
setup instruction changes

### ISSUE THREAD

**Issue by CaitlinBate** [ocean-tracking-network/2023-canssi-ecr-workshop#16]
- no more rgdal i think!
- intall geodata needed for pathroutr lesson
- install miscYAPS needs to be added for RObs lesson `library(remotes` `remotes::install_github("robertlennox/miscYAPS")`
- install glatos needs some extra steps rn --- see below

1) Download the archived tar.gz file for  [rgeos](https://cran.r-project.org/src/contrib/Archive/rgeos/)

2)  install.packages("C:/Users/caitl/Downloads/rgeos_0.6-4.tar.gz", repos = NULL, type = "source")

library(remotes) 
install_github('ocean-tracking-network/glatos', build_vignettes = TRUE)

**all of these changes need to be in THREE places --- gh-pahes `/resources/setup.doc` , `setup.R` and master `setup.md`**

**Comment by jackVanish** [comment]
@CaitlinBate 
Got two merge requests for this one- pages and master: 
 https://github.com/ocean-tracking-network/2023-canssi-ecr-workshop/pull/20
 https://github.com/ocean-tracking-network/2023-canssi-ecr-workshop/pull/21

Have a look and lemme know!

**Comment by jackVanish** [comment]
We'll need to tweak the setup again once Rob's lessons are in but since that's tracked well enough in #5, I think this can be closed.
