### ISSUE TITLE
Typos in Headers

### ISSUE THREAD

**Issue by slandovs** [ocean-tracking-network/2023-canssi-ecr-workshop#23]
section 2, 3, and 4 say "BACKGOUND" and should be "BACKGROUND"

**Comment by CaitlinBate** [comment]
todo:
- change in gh-pages, episodes. its the TITLE of each episode (within the markdown file) that need updating

**Comment by jackVanish** [comment]
Fix in here: https://github.com/ocean-tracking-network/2023-canssi-ecr-workshop/pull/24
